export const ActivityStrings = {
  Title: 'Activity',
  Description: 'What this phone observed during this connection session.',
  Observations: 'Observations',
  Diagnostics: 'Diagnostics',
  All: 'All',
  Issues: 'Issues',
  Filter: 'Filter',
  Latest: 'Latest',
  Details: 'View details',
  HideDetails: 'Hide details',
  Empty: 'No communication observed in this session',
  EmptyDetail:
    'Use a tool to submit a value, or inspect the existing diagnostics.',
  NoIssues: 'No failed operations observed',
  NoIssuesDetail: 'This is device-side history, not a cloud health report.',
  Interrupted: 'This session has ended. Reconnect to observe a new session.',
  Local: 'Observed by this app',
  Simulated: 'Simulation - no cloud traffic',
  Outbound: 'Phone to cloud',
  Inbound: 'Cloud to phone',
  NoOutbound: 'No outgoing observation in this session.',
  NoInbound: 'No incoming observation in this session.',
  NotReceipt: 'Local submission is not cloud receipt.',
  Session: 'Session generation',
  Device: 'Assigned device ID',
  Hub: 'Device-facing Hub',
  Model: 'Model declared by app',
  Request: 'Request identifier',
  Version: 'Desired-property version',
  Channel: 'Channel',
  Capability: 'Capability',
  Error: 'Safe error code',
  Http: 'HTTP status',
  Source: 'Property observation source',
  Reply: 'Handler response category',
  TelemetryHistory:
    'Periodic telemetry keeps only its latest outcome, not a row for every reading.',
  PhysicalLimit:
    'A handler outcome is not independent confirmation of a physical effect.',
  UploadChannel:
    'Image bytes use the storage upload channel, not MQTT telemetry.',
  TwinValue: 'Initial twin value',
  DesiredUpdate: 'Desired-property update',
  Channels: {
    telemetry: 'Telemetry',
    'reported-property': 'Reported property',
    'twin-request': 'Twin request',
    command: 'Command',
    'command-reply': 'Command response',
    'command-execution': 'Command handler',
    'desired-property': 'Desired property',
    'property-ack': 'Property acknowledgement',
    upload: 'Image upload',
  },
  Outcomes: {
    submitted: 'submitted locally',
    simulated: 'simulated locally',
    acknowledged: 'acknowledged over HTTP',
    failed: 'failed',
    observed: 'observed by this phone',
    completed: 'completed',
    requested: 'requested a change',
    rejected: 'rejected or failed',
  },
};
