export const ExperienceStrings = {
  Home: {
    Capability: 'IoT Plug and Play',
    Map: 'Connection',
    MapHint: 'Tap a node to understand its role and this setup.',
    CloudServices: 'Azure services',
    PhonePlatforms: {android: 'Android', ios: 'iPhone'},
    PathLabels: {dps: 'Assignment', hub: 'Messages'},
    MapLegend:
      'Solid: the phone\u2019s two-way links. Grey dashed: cloud coordination.',
    FlowHint: 'The light shows connection state, not message traffic.',
    Interrupted:
      'Red, broken: the phone\u2019s connection dropped. Reconnect in Connection details.',
    InterruptedAlert:
      'The phone\u2019s connection dropped. Reconnect in Connection details.',
    Disconnected:
      'Red, broken: you disconnected this phone. Reconnect in Connection details.',
    DisconnectedAlert:
      'You disconnected this phone. Reconnect in Connection details.',
    FlowNote:
      'While connected, a soft light drifts along the connectors. It is a decorative state indicator, not packets, throughput or delivery confirmation. DPS is contacted for assignment; it is not a persistent message path.',
    MapAuthority:
      'Relationships explained here are not a live Azure resource check.',
    NamespaceLinks: 'Namespace service links and Hub allocation configuration',
    PhoneDpsPath: 'Phone to and from DPS: assignment',
    PhoneHubPath: 'Phone to and from IoT Hub: device messages',
    OpenPanel: 'Open connection map details',
    Close: 'Close',
    Details: 'Connection details',
    DetailsHint:
      'Connection controls, diagnostics and credential maintenance remain in Details.',
    Simulation: 'Simulation - not a live cloud connection',
    SimulationIdentity: 'No live assignment is shown in simulation.',
    Unknown: 'Not available',
    NotChecked: 'Not checked',
    NotConfigured: 'Not configured',
    Hidden: 'Configured - hidden',
    PresenceOnly:
      'Presence only; not an independent validity check. Secret values are never shown or copied here.',
    InvalidSetup:
      'Setup identifiers could not be safely displayed. Review Connection details.',
    InvalidIdentity:
      'Connection identifiers could not be safely displayed. Review Connection details.',
    NoSetup:
      'No device setup is available. Use the existing Registration flow through Settings.',
    NoAssignment:
      'No assignment is available from the current client. A saved setup is not a live connection.',
    Sources: {
      Setup: 'Provided during setup',
      Dps: 'Returned by DPS',
      App: 'Declared by app',
      Generated: 'Generated by app',
      Snapshot: 'Imported snapshot',
      Azure: 'Managed in Azure',
      Local: 'Observed by this app',
    },
    Nodes: {
      adr: {
        Eyebrow: 'Operator setup',
        Title: 'ADR namespace',
        Subtitle: 'Service links + Hub allocation',
        Panel: 'Azure Device Registry',
        Role: 'The namespace coordinates linked DPS and eligible Hubs, including allocation configuration, and holds device inventory. Device messages flow between the phone and Hub, not through ADR.',
      },
      dps: {
        Eyebrow: 'Provisioning',
        Title: 'DPS',
        Subtitle: 'Assigns Hub + ID',
        Panel: 'Device Provisioning Service',
        Role: 'The phone requests an assignment. DPS returns the Hub endpoint and device identity; messaging then goes directly to that Hub. This app can request assignment again when reconnecting.',
      },
      hub: {
        Eyebrow: 'Where messages flow',
        Title: 'IoT Hub',
        Subtitle: 'Device messages',
        Panel: 'IoT Hub',
        Role: 'Telemetry and reported properties go to the Hub. Commands and desired properties arrive from it. Image bytes upload separately to the storage destination supplied for that operation.',
      },
      phone: {
        Eyebrow: 'This phone',
        Title: 'This phone',
        Subtitle: 'Device client',
        Panel: 'What the app holds',
        Role: 'The app uses device setup values to connect. It generates device-scoped SAS authentication locally; secret values stay out of these panels.',
      },
    },
    Fields: {
      Endpoint: 'Provisioning endpoint',
      Scope: 'ID scope',
      Registration: 'Registration ID',
      Model: 'Phone model ID',
      IndividualKey: 'Individual device key',
      GroupKey: 'Enrollment group key - legacy compatibility',
      ConnectionString: 'Device connection string',
      AssignedHub: 'Assigned Hub returned',
      AssignedDevice: 'Assigned device ID returned',
      Hub: 'Device-facing endpoint',
      Device: 'Device ID',
      Authentication: 'Authentication',
      Namespace: 'Namespace name',
      Captured: 'Snapshot captured at',
      Links: 'DPS / Hub link state',
      EligibleHubs: 'Eligible-Hub list',
      Inventory: 'Current inventory record',
      HistoricalInventory: 'Historical registry record name',
      Access: 'Azure access model',
    },
    EndpointNote:
      'The configured device-facing endpoint, not a named Azure management hostname.',
    RegistrationNote:
      'Provided for provisioning; it can differ from the assigned device ID.',
    ModelNote:
      'Describes phone capabilities. It is not a credential or a newly generated model.',
    GroupNote:
      'Legacy compatibility: a device key is derived locally from the supplied enrollment group key.',
    CredentialMaintenance:
      'Credential entry and deliberate reveal remain in Registration. Home never reveals key material.',
    DpsAuthentication: 'Device-scoped SAS from the individual device key',
    GroupAuthentication:
      'Device-scoped SAS from the locally derived device key',
    HubAuthentication: 'Device-scoped SAS token',
    AuthenticationNote:
      'Generated locally when connecting; token material is hidden. This describes the authentication method, not an active-token check.',
    NoAdminKey:
      'No additional Hub administrator key is needed. Connected does not establish cloud receipt or Azure management permissions.',
    DpsNotUsed: 'Not used in this setup',
    DirectRole:
      'This setup uses a device connection string. The phone bypasses DPS; the Hub and device identity come from setup instead of a provisioning assignment.',
    DirectIdentity:
      'Identifiers extracted from the saved device connection string. Their presence does not establish a current connection.',
    PhoneToHub: 'Phone to Hub',
    HubToPhone: 'Hub to phone',
    Outbound: 'Telemetry and reported properties',
    Inbound: 'Commands and desired properties',
    ManagedAccess: 'Operator-managed service identities and scoped roles',
    ManagedNote:
      'An authorized operator configures and inspects Azure resources. This app has not checked these roles or links.',
    NoManagement:
      'Device SAS does not grant Azure management or registry-read permission. No Azure administrator credential belongs on this phone.',
    SnapshotNote:
      'Historical operator-supplied context, not a live resource lookup or authenticated operator assertion.',
    NoSnapshot:
      'Optional Azure context is not available for this identity. It is not required to connect.',
    SnapshotOtherDevice:
      'Saved Azure context does not match the current identity. Review it in Connection details.',
    SnapshotUnavailable:
      'Saved Azure context could not be read. Review it in Connection details.',
    RegistryNote:
      'A historical snapshot does not establish the current registry record, eligible-Hub list or link health.',
    Attention: 'Needs attention',
    ConnectionAttention: 'Connection needs attention',
    ConnectionAttentionHint: 'Review the reported connection error in Details.',
    DisconnectedAttention: 'Disconnected on this phone',
    DisconnectedAttentionHint:
      'Your saved connection is kept. Reconnect in Details when you are ready.',
    SensorAttention: 'An enabled sensor is unavailable',
    SensorAttentionHint: 'Review enabled sources in Telemetry.',
    Communication: 'Latest observations',
    CommunicationEmpty: 'No communication observations are available here.',
    Activity: 'View Activity',
    ActivityHint: 'Opens the full observation and diagnostics trail.',
  },
};
