pool:
  vmImage: 'macos-latest'

name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:
- job: 'test'
  steps:
      - task: Bash@3
        displayName: 'list dlyb'
        inputs:
            targetType: inline
            script: 'ls -lh /Applications/Xcode_$(Xcode_Version).app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos'
      - task: Bash@3
        displayName: 'list dlyb swift'
        inputs:
            targetType: inline
            script: 'ls -lh /Applications/Xcode_$(Xcode_Version).app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos'      