trigger:
  - master
  - develop

pool:
  vmImage: 'macos-latest'

name: $(Date:yyyyMMdd)$(Rev:.r)
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.7.1'
  displayName: 'Install Node'

- script: npm install
  workingDirectory: .
  displayName: 'Install node dependencies'

- task: InstallAppleCertificate@2
  displayName: "Install Apple Certificate"
  inputs:
    certSecureFile: '$(Certificate_Name)'
    certPwd: '$(Certificate_Password)'
- task: InstallAppleProvisioningProfile@1
  displayName: "Install Apple provisioning profile"
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '$(Provisioning_Profile)'

- task: Shell++@0
  inputs:
    type: 'FilePath'
    scriptPath: 'bumpVersion.sh'

- task: Xcode@5
  displayName: "Build Mobile Application"
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos13.6'
    xcWorkspacePath: 'ios/$(Project_Name).xcworkspace'
    scheme: '$(Project_Name)'
    packageApp: true
    exportPath: 'output/package'
    archivePath: 'output/archive'
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_$(Xcode_Version).app/Contents/Developer'
  
- task: PublishBuildArtifacts@1
  displayName: "Publish Build Artifact"
  inputs:
    PathtoPublish: 'output/package/$(Project_Name).ipa'
    ArtifactName: 'drop'
    publishLocation: 'Container'