require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

target 'iotc_pad_client' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'RNSensors', :path => '../node_modules/react-native-sensors'

  target 'iotc_pad_clientTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end
  end
end

target 'iotc_pad_client-tvOS' do
  # Pods for iotc_pad_client-tvOS

  target 'iotc_pad_client-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
